### ISSUE TITLE
Travis setup is broken

### ISSUE THREAD

**Issue by simonlindholm** [indaplusplus/ajafer-chess#2]
Note the execution log here: https://travis-ci.org/indaplusplus/ajafer-chess/builds/281073559

It's suspiciously short, makes no note of tests, and includes the line:

```
[WARNING] JAR will be empty - no content was marked for inclusion!
```

Seems like `mvn clean verify` "works", but just outputs an empty jar file. Probably needs some config, or different organization of source files.

(Would be good practice to submit a failing test as a Pull Request, to see that Travis really tests what you think it tests!)

**Comment by ajafer** [comment]
@simonlindholm I think it's testing correctly now?
https://travis-ci.org/indaplusplus/ajafer-chess

**Comment by simonlindholm** [comment]
`Tests run: 0, Failures: 0, Errors: 0, Skipped: 0` sounds worrying... Let me make a PR that breaks something to test whether it's working.

**Comment by simonlindholm** [comment]
Yep, seems like travis does test building the project, so #3 fails as it should, but it doesn't run the tests, so #4 succeeds though it shouldn't.

**Comment by s4wny** [comment]
@ajafer

**Comment by ajafer** [comment]
@simonlindholm I think it's fixed now! :)

**Comment by s4wny** [comment]
Yupp, it's fixed. Tested with https://github.com/indaplusplus/ajafer-chess/pull/6
